sudo: false

language: node_js

node_js:
  - "7"
  - "6"
  - "5"
  - "4"
  - "0.10"
  - "0.12"
  - "iojs"

git:
  depth: 1

cache:
  yarn: true
  directories:
    - node_modules

notifications:
  email: false
